### ISSUE TITLE
Extension error, not sure what this means? Using Thorium for ZorinOS.

### ISSUE THREAD

**Issue by Username23453** [Erisa/download-image#17]
Using thorium browser: github.com/Alex313031/thorium.

heres the error i get, dont know what it means:

![image](https://github.com/Erisa/download-image/assets/105397593/09cc2bb8-294e-443c-b977-68b46bda5c3f)

**Comment by Erisa** [comment]
That's a warning, not an error, and is expected in order for Firefox to be supported by the same manifest.This can be ignored.
